<HomePage>
    GridLayout:
        cols: 1
        size: root.width, root.height 

        GridLayout:
            cols: 2
            
            Label:
                text: "Temperature:"

            TextInput:
                multiline: False
            
            Label:
                text: "Time:"

            TextInput:
                multiline: False
                        
        Button:
            text: "Submit"